### ISSUE TITLE
Enable additional Go linters, fix issues they flag

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#1113]
**What would you like to be added**:

Enable the commented golangci-lint linters in each repo's `.golangci.yml`, or rule them out as potentially useful and remove them.

For example, from this repo:

```
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      # - performance
      - style
```

```
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    # - dupl
    - errcheck
    - exportloopref
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    # - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    # - stylecheck
    # - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl
```

https://github.com/submariner-io/submariner/blob/master/.golangci.yml

**Why is this needed**:

When doing the major set of linting refactoring that added golangcl-lint, I didn't want to continue working on enabling Go linters before taking a first pass at the many other types of linting I wanted to add. I included these commented out linters as a starting point for later, as they seemed to flag real, non-duplicate areas for improvement. Now that we have broad linting coverage, we should loop back and dig deeper into enabling Go linters and fixing the issues they flag.
