### ISSUE TITLE
Exporting multiple headless services with Globalnet does not work

### ISSUE THREAD

**Issue by kevinanderson1** [submariner-io/submariner#1634]
**What happened**: Exporting multiple services with globalnet does not allocate a globalnet ingress ip `giip` per exported service and instead only creates one and in some cases overwrites it and in others deletes it. This breaks connectivity when using globalnet and exporting more than one service per cluster. If globalnet is restarted you can see the globalnet controller iterating through the exported services and reusing the same globalnet ingress ip and deleting objects without allocating an ip.

**What you expected to happen**: I expect each exported service to get a unique globalnet ingress ip which is published to the broker and synced to other clusters.

**How to reproduce it (as minimally and precisely as possible)**: 
1. Create kind-dup.yaml
```yaml
# kind-dup.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "192.168.100.244" # Update this to your local IP for you system. Had to do this to work around some other issues
  podSubnet: "10.42.0.0/16"
  serviceSubnet: "10.43.0.0/16"
nodes:
- role: control-plane
- role: worker
```
2. `kind create cluster --name cluster-dup-1 --config ./kind-dup.yaml `
3. `kind create cluster --name cluster-dup-2 --config ./kind-dup.yaml `
4. `kubectl config set-context cluster-dup-1`
5. `subctl deploy-broker --globalnet --globalnet-cidr-range 10.24.0.0/16 --globalnet-cluster-size 2048`
6. `subctl join broker-info.subm `
7. `kubectl config set-context cluster-dup-2`
8. `subctl join broker-info.subm`
9.  Deploy multiple services. I used this sample YAML (stateful-set.yaml)
`kubectl apply -f stateful-set.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-r0
  labels:
    app: nginx-r0
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-r0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-r0
spec:
  selector:
    matchLabels:
      app: nginx-r0 # has to match .spec.template.metadata.labels
  serviceName: "nginx-r0"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-r0 # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-r1
  labels:
    app: nginx-r1
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-r1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-r1
spec:
  selector:
    matchLabels:
      app: nginx-r1 # has to match .spec.template.metadata.labels
  serviceName: "nginx-r1"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-r1 # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-r2
  labels:
    app: nginx-r2
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-r2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-r3
spec:
  selector:
    matchLabels:
      app: nginx-r2 # has to match .spec.template.metadata.labels
  serviceName: "nginx-r2"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-r2 # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
```
11. Export the services
* `subctl export service nginx-r0`
* `subctl export service nginx-r1`
* `subctl export service nginx-r2`
12. Check the current `giip` assignments with `kubectl get giip -A`. I expect there to be only one when there should be at least 3 in this case.
13. Setup a watch on the `giip` resource in a separate terminal window with `kubectl get giip --watch -n default` and delete the submariner-globalnet pod to have it sync the `giip` CRD's. The output of the watch command is provided below.
```bash
kubectl get giip --watch -n default
NAME             IP
pod-nginx-r3-0   10.24.15.253
pod-nginx-r0-0   
pod-nginx-r3-0   10.24.15.253
pod-nginx-r1-0   
pod-nginx-r0-0   10.24.15.252
pod-nginx-r0-0   10.24.15.252
pod-nginx-r3-0   
pod-nginx-r1-0   10.24.15.253
pod-nginx-r1-0   10.24.15.253
pod-nginx-r3-0   10.24.15.252
```

**Anything else we need to know?**: I believe this is isolated to clusters utilizing Globalnet but I did not verify that multiple exported services per cluster works without globalnet. Additionally this occurs in 0.10 and 0.11.

**Environment**:
- Diagnose information (use `subctl diagnose all`):
```
Cluster "kind-cluster-dup-1"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.21.1" is supported

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("generic") is supported

 ✓ Checking gateway connections
 ✓ All connections are established

 ✓ Checking Submariner pods
 ✓ All Submariner pods are up and running

 ✓ Globalnet deployment detected - checking if globalnet CIDRs overlap
 ✓ Clusters do not have overlapping globalnet CIDRs

 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported

 ✓ Checking the firewall configuration to determine if the metrics port (8080) is allowed 
 ✓ The firewall configuration allows metrics to be retrieved from Gateway nodes

 ✓ Checking the firewall configuration to determine if VXLAN traffic is allowed 
 ✓ The firewall configuration allows VXLAN traffic

Skipping tunnel firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall tunnel" command manually.

Cluster "kind-cluster-dup-2"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.21.1" is supported

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("generic") is supported

 ✓ Checking gateway connections
 ✓ All connections are established

 ✓ Checking Submariner pods
 ✓ All Submariner pods are up and running

 ✓ Globalnet deployment detected - checking if globalnet CIDRs overlap
 ✓ Clusters do not have overlapping globalnet CIDRs

 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported

 ✓ Checking the firewall configuration to determine if the metrics port (8080) is allowed 
 ✓ The firewall configuration allows metrics to be retrieved from Gateway nodes

 ✓ Checking the firewall configuration to determine if VXLAN traffic is allowed 
 ✓ The firewall configuration allows VXLAN traffic

Skipping tunnel firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall tunnel" command manually.
```
- Gather information (use `subctl gather`): If needed I can gather these.
- Cloud provider or hardware configuration: kind clusters on my laptop but also Rancher Kubernetes 1.19 installations with Canal networking.
- Install tools: N/A
- Others: N/A
