### ISSUE TITLE
Use helm install submariner， how to Run the verification

### ISSUE THREAD

**Issue by 631068264** [submariner-io/submariner#1963]
**What happened**:

Follow https://submariner.io/operations/deployment/helm/ to install.

Three clusters I have ,  one is host cluster , the other two cluster is member.

Installed  broker and subctl  on host cluster , submariner-operator  on two member clusters.

```
KUBECONFIG=member1-config:member2-config subctl verify --kubecontexts member1,member2 --only service-discovery,connectivity --verbose
Performing the following verifications: service-discovery, connectivity
Running Suite: Submariner E2E suite
===================================
Random Seed: 1660631360
Will run 37 of 41 specs

STEP: Creating kubernetes clients
STEP: Creating lighthouse clients
Failure [240.028 seconds]
[BeforeSuite] BeforeSuite 
github.com/submariner-io/shipyard@v0.13.0/test/e2e/e2e.go:42

  Failed to find Clusters to detect if Globalnet is enabled. No Cluster found
  Unexpected error:
      <*errors.errorString | 0xc0002148b0>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  occurred

  github.com/submariner-io/shipyard@v0.13.0/test/e2e/framework/framework.go:517
------------------------------

Ran 37 of 0 Specs in 240.044 seconds
FAIL! -- 0 Passed | 37 Failed | 0 Pending | 0 Skipped
[] E2E failed

subctl version: v0.13.0
```

install values.yaml
```
---
submariner:
  clusterId: "xxx"
  clusterCidr: "xxx"
  serviceCidr: "xxx"
  images:
    repository: private-repo/submariner
    tag: "0.12.2"
broker:
  server: "${SUBMARINER_BROKER_URL}"
  token: "${SUBMARINER_BROKER_TOKEN}"
  namespace: "submariner-broker"
  ca: "${SUBMARINER_BROKER_CA}"
ipsec:
  psk: "${SUBMARINER_PSK}"
operator:
  image:
    repository: private-repo/submariner/submariner-operator
    tag: "0.12.2"
gateway:
  image:
    repository: private-repo/submariner/submariner-gateway
    tag: "0.12.2"


```

on member cluster
```
kubectl get pods -n submariner-operator
NAME                                            READY   STATUS    RESTARTS   AGE
submariner-lighthouse-agent-6dd4bc9b4b-ft6cq    1/1     Running   0          3h15m
submariner-lighthouse-coredns-8bf8fccdb-92kpd   1/1     Running   0          3h15m
submariner-lighthouse-coredns-8bf8fccdb-gxpxs   1/1     Running   0          3h15m
submariner-operator-d4cd68cb9-4qdv5             1/1     Running   1          3h15m
submariner-routeagent-8mwrh                     1/1     Running   0          3h15m
```

- Cloud provider or hardware configuration:
- Install tools:  helm3  submariner-k8s-broker-0.12.2.tgz  submariner-operator-0.12.2.tgz
- Others:
