### ISSUE TITLE
Connection between two clusters error

### ISSUE THREAD

**Issue by USER0308** [submariner-io/submariner#2724]
Env:
subctl 0.15.2
Two k8s clusters created by kubeadm.
Cluster-1 has a single node, act as master and worker,  with `submariner.io/gateway=true` label.
Cluster-2 has two nodes, one is master and another is worker node.

Cluster-1 is used as broker.
Both cluster-1 and cluster-2 are joined into the broker, and all pods are running normally.

When adding label `submariner.io/gateway=true` to cluster-2 master node, all pods are running. But the network connection is error when running `subctl show all` in both cluster-1 and cluster-2.
cluster-1 -> cluster-2, connection error
![image](https://github.com/submariner-io/subctl/assets/19644336/71c87361-6a5b-4869-96c7-a2b38da681a4)

cluster-2 -> cluster-1, connection error
![image](https://github.com/submariner-io/subctl/assets/19644336/ae1abb7d-3b1f-4252-8683-b51b515ae8ba)

When adding label `submariner.io/gateway=true` to cluster-2 worker node, all pods are running. And the network from cluster-2 to cluster-1 is ok when running `subctl show all` in cluster-2. But cluster-1 to cluster-2 is error when running `subctl show all` in cluster1.

cluster-1 -> cluster-2, connection error
![image](https://github.com/submariner-io/subctl/assets/19644336/5461dc5a-8786-4ce5-960d-46becbedc1f8)

cluster-2 -> cluster-1, connection ok
![image](https://github.com/submariner-io/subctl/assets/19644336/4ab433d3-951c-404f-bfb0-fdc9e26bf4c8)

Is this connection error related to the node number?
Is cluster with only one nodes supported to join into the broker?
Do each cluster require at least two nodes(one for master and another for worker)?

**Comment by USER0308** [comment]
Solved!
Connection ok is because I have create an IPPool before in cluster-2.
```
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: yyy
spec:
  cidr: 242.1.0.0/16
  disabled: true
  natOutgoing: false
```
After creating an IPPool in cluster-1, connection is ok
```
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: xxx
spec:
  cidr: 242.0.0.0/16
  disabled: true
  natOutgoing: false
```

New question: 
If I have n clusters, should I create n-1 IPPool to config their cidr manually?
Can I set cidr as 242.0.0.0/8 in all of the cluster's IPPool?
