### ISSUE TITLE
diagnose all are ok,but can not inter cluster connect,calico network ,has set ippool

### ISSUE THREAD

**Issue by 13567436138** [submariner-io/submariner#2810]
**What happened**:
```
[root@worker-01 ~]# subctl diagnose all --kubeconfig ~/153config 
Cluster "cluster1"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.28.1" is supported

 ✓ Non-Globalnet deployment detected - checking that cluster CIDRs do not overlap
 ✓ Checking DaemonSet "submariner-gateway"
 ✓ Checking DaemonSet "submariner-routeagent"
 ✓ Checking DaemonSet "submariner-metrics-proxy"
 ✓ Checking Deployment "submariner-lighthouse-agent"
 ✓ Checking Deployment "submariner-lighthouse-coredns"
 ✓ Checking the status of all Submariner pods
 ✓ Checking that gateway metrics are accessible from non-gateway nodes 

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("calico") is supported
 ✓ Calico CNI detected, checking if the Submariner IPPool pre-requisites are configured
 ✓ Checking gateway connections
 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported
 ✓ Checking that firewall configuration allows intra-cluster VXLAN traffic 

 ✓ Checking that services have been exported properly


Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.
[root@worker-01 ~]# subctl diagnose firewall inter-cluster --kubeconfig 153config --remoteconfig 156config 
 ✓ Checking if tunnels can be setup on the gateway node of cluster "cluster1" 
 ✓ Tunnels can be established on the gateway node of cluster "cluster1"
```

```
[root@worker-01 ~]# subctl show all --kubeconfig 153config 
Cluster "cluster1"
 ✓ Detecting broker(s)
 ✓ No brokers found

 ✓ Showing Connections
GATEWAY       CLUSTER   REMOTE IP         NAT   CABLE DRIVER   SUBNETS                       STATUS      RTT avg.     
member2-156   member2   192.168.229.156   no    libreswan      10.70.0.0/16, 172.22.0.0/16   connected   629.446µs    

 ✓ Showing Endpoints
CLUSTER   ENDPOINT IP       PUBLIC IP      CABLE DRIVER   TYPE     
member1   192.168.229.153   39.189.13.59   libreswan      local    
member2   192.168.229.156   39.189.13.59   libreswan      remote   

 ✓ Showing Gateways
NODE          HA STATUS   SUMMARY                               
member1-153   active      All connections (1) are established   

 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  calico
        Service CIDRs:   [10.69.0.0/16]
        Cluster CIDRs:   [172.21.0.0/16]

 ✓ Showing versions 
COMPONENT                       REPOSITORY           CONFIGURED   RUNNING                     ARCH    
submariner-gateway              quay.io/submariner   0.16.2       release-0.16-88f54d25ccfc   amd64   
submariner-routeagent           quay.io/submariner   0.16.2       release-0.16-88f54d25ccfc   amd64   
submariner-metrics-proxy        quay.io/submariner   0.16.2       release-0.16-3d7d32af4808   amd64   
submariner-operator             quay.io/submariner   0.16.2       release-0.16-d4284df96925   amd64   
submariner-lighthouse-agent     quay.io/submariner   0.16.2       release-0.16-847b34cf06d0   amd64  
```
**What you expected to happen**:
[root@member1-153 ~]# kubectl exec -it -n karmada busybox-fc8bdbbf7-vwqzs sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
/ # wget nginx.karmada.svc.clusterset.local
Connecting to nginx.karmada.svc.clusterset.local (10.70.109.85:80)

```
in cluster2:

[root@member2-156 ~]# kubectl get svc -n karmada
NAME    TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
nginx   ClusterIP   10.70.109.85   <none>        80/TCP    15h
[root@member2-156 ~]# curl 10.70.109.85
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

svcwestcluster-cluster1.yaml

kubectl apply -f svcwestcluster-cluster1.yaml --kubeconfig ~/153config

kubectl apply -f svcwestcluster-cluster1.yaml --kubeconfig ~/156config

```
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: svcwestcluster
spec:
  cidr: 10.69.0.0/16
  natOutgoing: false
  disabled: true
  vxlanMode: Always
```

podwestcluster-cluster1.yaml

kubectl apply -f podwestcluster-cluster1.yaml --kubeconfig ~/153config

kubectl apply -f  podwestcluster-cluster1.yaml --kubeconfig ~/156config

```
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: podwestcluster
spec:
  cidr: 172.21.0.0/16
  natOutgoing: false
  disabled: true
  vxlanMode: Always
```

svceastcluster-cluster2.yaml

kubectl apply -f svceastcluster-cluster2.yaml  --kubeconfig ~/153config

kubectl apply -f  svceastcluster-cluster2.yaml  --kubeconfig ~/156config

```
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: svceastcluster
spec:
  cidr: 10.70.0.0/16
  natOutgoing: false
  disabled: true
  vxlanMode: Always
```

podeastcluster-cluster2.yaml

kubectl apply  -f podeastcluster-cluster2.yaml --kubeconfig ~/153config

kubectl apply -f  podeastcluster-cluster2.yaml --kubeconfig ~/156config

```
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: podeastcluster
spec:
  cidr: 172.22.0.0/16
  natOutgoing: false
  disabled: true
  vxlanMode: Always
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
[submariner-20231124033358.zip](https://github.com/submariner-io/submariner/files/13454910/submariner-20231124033358.zip)

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:
