### ISSUE TITLE
Cross clusters DNS discovery

### ISSUE THREAD

**Issue by Negashev** [submariner-io/submariner#3]
What about dns discovery like cilium
![multicluster-d571ea42066d163634133cf758ef45a8-1f0d9](https://user-images.githubusercontent.com/4653589/54294676-b25e3080-45c2-11e9-94e6-656ce5036ce1.png)

**Comment by Oats87** [comment]
This concept has been on our road map, where Submariner will run a controller that will synchronize service/endpoint objects between clusters.

**Comment by Negashev** [comment]
@Oats87 Amazing! Will wait!

**Comment by Negashev** [comment]
Some solution
We can add cluster with coredns service ip 10.60.60.60 and Corefile
```
.:53 {
    etcd coredns.submariner {
        path /skydns
        endpoint http://etcd-service:2379
    }
    cache 10
    loadbalance round_robin
    errors
    health
    log
}
```


- install external dns (to etcd for coredns) on all clusters
- add stubDomains for clusters
```yaml
apiVersion: v1
data:
  stubDomains: '{"coredns.submariner": ["10.60.60.60"]}'
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
```
