### ISSUE TITLE
GlobalNet does not assign a global IP to my Service object 

### ISSUE THREAD

**Issue by orimanabu** [submariner-io/submariner#864]
**What happened**:
I created a Service object and waited for over 1 hour, but could not get global IP.

**What you expected to happen**:
My service object gets global IP from GlobalNet.

**How to reproduce it (as minimally and precisely as possible)**:
1. Preparation: deploy pods using following script
```
#!/bin/bash

cat << END | kubectl apply -f -
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: paulbouwer/hello-kubernetes:1.8
        ports:
        - containerPort: 8080
END
```

2. Run following script to create a Service object
```
#!/bin/bash

cat << END | kubectl apply -f -
---
apiVersion: v1
kind: Service
metadata:
  name: test1
  labels:
    app: test
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: test
END
```

3. Wait for a global IP to be assigned to the Service... but never assigned.

**Anything else we need to know?**:
I found that adding `spec.ports[*].name = http` to the Service resolved the issue.
I run the following script, then the Service got global IP successfully.
```
#!/bin/bash

cat << END | kubectl apply -f -
---
apiVersion: v1
kind: Service
metadata:
  name: test2
  labels:
    app: test
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: http  # <= added this line
  selector:
    app: test
END
```

**Environment**:
- Submariner version (use `subctl version`): `subctl version: v0.6.1`
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: KVM Virtual Machines
- OS (e.g: `cat /etc/os-release`): 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`): `Linux site2-master1 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm v1.19.2
- Network plugin and version (if this is a network-related bug): Weave 2.7.0
- Others:
