### ISSUE TITLE
Error from server (NotFound): serviceexports.lighthouse.submariner.io not found

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#957]
When using the default kubeconfig namespace, e.g.:
 
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
https://api.default-cl2.devcluster.openshift.com:6443
  name: default-cl2
contexts:
- context:
    cluster: default-cl2
    namespace: test-submariner
    user: admin
  name: pkomarov-cluster-b
current-context: pkomarov-cluster-b
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
https://api.default-cl2.devcluster.openshift.com:6443
```

And creating + exporting a service without specifying namespace:
```
deployment.apps/nginx-cl-b created
service/nginx-cl-b exposed
Service exported successfully

Name:         nginx-cl-b-55668cf7cd-zbk72
Namespace:    test-submariner-headless
Priority:     0
Node:         default-cl2-srrk7-worker-ct748/10.2.1.169
Start Time:   Sun, 22 Nov 2020 15:24:45 +0200
Labels:       app=nginx-cl-b
              pod-template-hash=55668cf7cd
Annotations:  k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "10.139.0.138"
                    ],
                    "dns": {},
                    "default-route": [
                        "10.139.0.1"
                    ]
                }]
              openshift.io/scc: restricted
Status:       Running
IP:           10.139.0.138
IPs:
  IP:           10.139.0.138
Controlled By:  ReplicaSet/nginx-cl-b-55668cf7cd
Containers:
  nginx-unprivileged:
    Container ID:   cri-o://9c84e61db09535b253a171a74e46869140249f9b21e0aa9b45bc0338d494f119
    Image:          nginxinc/nginx-unprivileged:stable-alpine
    Image ID:       docker.io/nginxinc/nginx-unprivileged@sha256:ea172be265100e026b7ef8465d2e5887ced61ce54a670476f9385b6daf0b3b95
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Sun, 22 Nov 2020 15:24:47 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-nxn5t (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-nxn5t:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-nxn5t
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  24s   default-scheduler  Successfully assigned test-submariner-headless/nginx-cl-b-55668cf7cd-zbk72 to default-cl2-srrk7-worker-ct748
  Normal  Pulled     52s   kubelet            Container image "nginxinc/nginx-unprivileged:stable-alpine" already present on machine
  Normal  Created    52s   kubelet            Created container nginx-unprivileged
  Normal  Started    52s   kubelet            Started container nginx-unprivileged
```

The service does not show "Exported" even after 3 minutes:

```
$ oc  describe serviceexport nginx-cl-b
Error from server (NotFound): serviceexports.lighthouse.submariner.io "nginx-cl-b" not found
```

**What happened**:
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS-No-Overlapping/88/Test-Report/
(pod logs at the end)

**Environment**:

Submariner:
subctl version: v0.7.0-54-g72d40d3

OCP cluster A (AWS):
Client Version: 4.6.4
Server Version: 4.6.4
Kubernetes Version: v1.19.0+9f84db3

OCP cluster B (OSP):
Client Version: 4.6.4
Server Version: 4.4.7
Kubernetes Version: v1.17.1+f5fb168
